### ISSUE TITLE
Investigate errors and refactoring

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/MobilitySimulator#62]

**Comment by sebastian-peter** [comment]
Thanks for tackling this task! While I'm seeing the _refactoring_ part of this issue title, please be aware that @staudtMarius and me are doing exactly that in various PRs. So, some issues might even be tackled already.

**Comment by t-ober** [comment]
Thanks for letting me know. We should definitely have another discussion on how we approach this. I have a few suggestions for how to approach the refactoring.

**Comment by t-ober** [comment]
We are on it. This will be replaced with more specific issues!
